title: Niel Haldane G. Ramos
logo: /assets/images/logo.png  # Add your logo image here
description: "A passionate software developer and tech enthusiast, exploring the world of code."
show_download: true

# Link to your custom CSS for logos and hover effects
styles:
  - /assets/css/custom.css  # Make sure the path is correct

# Theme settings
theme: jekyll-theme-merlot
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag  
  - jekyll-feed    

# Header pages to navigate between sections
header_pages:
  - Home: /
  - About: /about
  - Projects: /projects
  - Contact: /contact

# Social media links
social_links:
  github: "https://github.com/NielRamos-CS"
  linkedin: "https://www.linkedin.com/in/niel-haldane-ramos-28ba85337/"

# Optional: Add any other customizations you want here
exclude:
  - README.md
